/** @format */

export const ValidationText = {
  Title: "제목을 입력해주세요",
  Content: "내용을 입력해주세요",
  UserName: "이용자명 입력해주세요",
  Password: "비밀번호 입력해주세요",
  NewPassword: "새 비밀번호를 입력해주세요",
  Character: "문자를 입력해주세요",
  Images: "사진을 선택해주세요",
  Question: "문의 내용을 입력해주세요",
  Answer: "답변을 입력해주세요",
  CompanySelect: "입점사를 선택해주세요",
  BranchSelect: "지점을 선택해주세요",
  CompanyName: "입점사명을 입력해주세요",
  Pictogram: "픽토그램을 선택해주세요",
  MainPhoto: "대표사진을 선택해주세요",
  ProductSize: "상품 사이즈를 입력해주세요",
  Price: "상품 가격을 입력해주세요",
  Deposit: "상품 보증금을 입력해주세요",
  Quantity: "수량을 입력해주세요",
  PurchaseLimit: "구매 제한 수량 입력해주세요",
  AvailableDay: "예약가능일을 입력해주세요",
  QuantityBoxes: "박스 수량을 입력해주세요",
  MinUsage: "최소 이용 기간을 입력해주세요",

  BrandName: "브랜드명을 입력하세요.",
  RegistrationName: "사업자등록상호명을 입력해주세요",
  RegistrationNumber: "사업자등록번호를 입력하세요.",
  ResidentRegistrationNumber: "주민등록번호 입력하세요.",
  Address: "사업장 주소지를 입력하세요.",
  ID: "Please input your ID",
  Name: "대표자 이름을 입력하세요.",
  Phone: "대표자 연락처를 입력하세요.",
  Email: "대표자 이메일을 입력하세요.",
  SettlementCreditAccount: "정산대금 입금계좌를 입력하세요.",
  BranchName: "지점명을 입력해주세요",
  Notice: "공지사항을 입력해주세요",
  BusinessInfo: "영업정보를 입력해주세요",
  RefundPolicy: "환불정책을 입력해주세요",
  Position: "직위를 입력해주세요",
  RequiredPassword:
    "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$",
  Keywords: "키워드 입력해주세요",
  Coordinate: "Coordinate 입력해주세요",

  Null: "Please enter data ",
};
